baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'PMR3304 Site - Entrega 1'
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true